---
- name: Lets copy our executable script to remote location execute script and get result back
  become: yes
  hosts: lab
  tasks:
     - name: Transfer executable script script
       copy: src=/home/vkchlt0188/Documents/test dest=/home/vkchlt0294/bibin mode=0777 