
---
- name: mount samba share to test pc
  hosts: lab
  become: yes
  tasks:   
           
           
    - name: mount smb_share
      ansible.posix.mount:
              state: "mounted"
              fstype: "cifs"
              path: /bitNxsa
              src: "//172.25.4.100/bitNxsa"
              opts: "credentials=/root/smb_pwd,file_mode=0777,dir_mode=0777,gid=root,uid=root"


 