---
- name: Create a cron job
  hosts: localhost
  become: true
  tasks:
    - name: Schedule cron
      cron:
        name: This job is scheduled by Ansible
        minute: "*"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        user: bibin
        job: "/home/bibin/Documents/bash/01test.sh"
          