---
- name: Lets copy our executable script to remote location execute script and get result back
  become: yes
  hosts: 
  tasks:



    - name: mount smb_share
      ansible.posix.mount:
              state: "mounted"
              fstype: "cifs"
              path: /bitNxsa
              src: "//172.25.4.100/bitNxsa"
              opts: "credentials=/root/smb_pwd,file_mode=0777,dir_mode=0777,gid=root,uid=root"