---
- name: Lets copy our executable script to remote location execute script and get result back
  become: yes
  hosts: lab
  tasks:
    
    - name: Execute the command
      shell: "dmidecode -t 1 "
      register: os_info

    - debug:
            msg: "{{os_info.stdout_lines}}"
     