---
- hosts: test
  tasks:

     - name: Create a script that will install packages for NDZ pc
       become: yes
       copy:
         content: |
            #!/usr/bin/bash
            sudo apt-get update
            sudo apt install git -y
            sudo apt install net-tools -y
            sudo apt install python3 -y
            sudo apt-get install vlc -y
            sudo apt install vim -y
            sudo apt install pidgin -y
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo apt update
            sudo apt --fix-broken install
            sudo rm /etc/apt/preferences.d/nosnap.pref
            sudo apt update
            #sudo apt install snapd
            #sudo systemctl start snapd
            #sudo systemctl enable snapd
            #sudo snap install postman
            sudo apt update 
            sudo apt install filezilla -y
            sudo apt update
            cd /tmp/ 
            sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb -y
            sudo rm google-chrome-stable_current_amd64.deb
            sudo wget https://go.skype.com/skypeforlinux-64.deb
            sudo apt install ./skypeforlinux-64.deb -y
            sudo rm skypeforlinux-64.deb
            sudo wget https://download.anydesk.com/linux/deb/anydesk_6.0.1-1_amd64.deb
            sudo apt install ./anydesk_6.0.1-1_amd64.deb -y
            sudo rm anydesk_6.0.1-1_amd64.deb
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo apt --fix-broken install -y
            sudo wget https://filestore.fortinet.com/forticlient/forticlient_vpn_7.0.7.0246_amd64.deb
            sudo apt install ./forticlient_vpn_7.0.7.0246_amd64.deb -y
            sudo rm forticlient_vpn_7.0.7.0246_amd64.deb
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo wget https://az764295.vo.msecnd.net/stable/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/code_1.82.2-1694671812_amd64.deb
            sudo apt install ./code_1.82.2-1694671812_amd64.deb -y
            sudo rm code_1.82.2-1694671812_amd64.deb
            sudo wget http://ftp.us.debian.org/debian/pool/main/p/pangox-compat/libpangox-1.0-0_0.0.2-5.1_amd64.deb
            sudo dpkg -i ./libpangox-1.0-0_0.0.2-5.1_amd64.deb 
            sudo rm libpangox-1.0-0_0.0.2-5.1_amd64.deb 
            YOUR_FILE='/etc/ssh/sshd_config'
            TEXT="#PermitRootLogin prohibit-password"
            sed -i "s/$TEXT/PermitRootLogin yes/" $YOUR_FILE
            sudo service sshd restart


          
         dest: /tmp/install.sh
         mode: 0755

     - name: Run the script 
       become: yes
       
       shell: sh /tmp/install.sh


     
     
     
