---
- hosts: lab
  tasks:

     - name: Create a script that will install packages for NDZ pc
       become: yes
       copy:
         content: |
            #!/usr/bin/bash
            sudo apt-get update
            sudo apt install git -y
            sudo apt install net-tools -y
            sudo apt install python3 -y
            sudo apt-get install vlc -y
            sudo apt install vim -y
            sudo apt install pidgin -y
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo apt update
            sudo apt --fix-broken install
            sudo rm /etc/apt/preferences.d/nosnap.pref
            sudo apt update
            sudo apt install snapd
            sudo systemctl start snapd
            sudo systemctl enable snapd
            sudo snap install postman
            sudo apt update 
            sudo apt install filezilla -y
            sudo apt install python3-virtualenv -y
            sudo apt install python3-pip -y
            sudo apt update
            sudo apt install python2 -y
            curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
            sudo python2 get-pip.py
            sudo python2 -m pip install virtualenv
            sudo apt update
            cd /tmp/ 
            sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb -y
            sudo rm google-chrome-stable_current_amd64.deb
            sudo snap install teams-for-linux
      
            sudo wget https://download.anydesk.com/linux/anydesk_6.3.2-1_amd64.deb
            sudo apt install ./anydesk_6.3.2-1_amd64.deb -y
            sudo rm anydesk_6.3.2-1_amd64.deb
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo apt --fix-broken install -y
            sudo apt update
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo wget http://ftp.us.debian.org/debian/pool/main/p/pangox-compat/libpangox-1.0-0_0.0.2-5.1_amd64.deb
            sudo dpkg -i ./libpangox-1.0-0_0.0.2-5.1_amd64.deb 
            sudo rm libpangox-1.0-0_0.0.2-5.1_amd64.deb 
            cd /home/ndimensionz
            YOUR_FILE='/etc/ssh/sshd_config'
            TEXT="#PermitRootLogin prohibit-password"
            sed -i "s/$TEXT/PermitRootLogin yes/" $YOUR_FILE
            sudo service sshd restart
            sudo rm /var/lib/dpkg/lock 
            sudo rm /var/cache/apt/archives/lock
            sudo dpkg --configure -a
            sudo apt install -f
            sudo apt-get upgrade -y
            sudo wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_23.04/Release.key -O - | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/owncloud-client.gpg > /dev/null
            sudo apt update
            sudo apt install apt-transport-https
            sudo echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_23.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud-client.list
            sudo apt update
            sudo apt install owncloud-client
            sudo apt-get install -f
          
         dest: /tmp/install.sh
         mode: 0755

     - name: Run the script 
       become: yes
       
       shell: sh /tmp/install.sh

     - name: Copy .deb file to remote /tmp
      copy:
        src: /home/bibin/linux/
        dest: /tmp/linux/
        mode: '0644'

    - name: Install the Visual code studio using dpkg
      command: dpkg -i /tmp/linux/code_1.100.3-1748872405_amd64.deb -y
      register: dpkg_result
      ignore_errors: yes

    - name: command
      shell: sudo apt-get install -f -y 
  

    - name: Install the forticlient VPN using dpkg
      command: dpkg -i /tmp/linux/forticlient_vpn_7.4.3.1736_amd64.deb -y
      register: dpkg_result
      ignore_errors: yes

    - name: Fix missing dependencies (if any)
      apt:
        update_cache: yes
        upgrade: no
        state: latest
      when: dpkg_result.rc != 0
          
     
  
     
     
     
