---
- name: Install LAMP stack and PHPMyAdmin
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

   

    - name: Install PHPMyAdmin
      apt:
        name: phpmyadmin
        state: present

    - name: Configure Apache for PHPMyAdmin
      template:
        src: phpmyadmin.conf.j2
        dest: /etc/apache2/sites-available/phpmyadmin.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted