---
- name: Install LAMP stack and PHPMyAdmin
  hosts: localhost
  become: true

  tasks:
   

    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation (optional, configure as needed)
      mysql_user:
        name: root
        host: "{{ ansible_default_ipv4.address }}"
        password: your_root_password
        priv: '*.*:ALL,GRANT'

    - name: Install PHPMyAdmin
      apt:
        name: phpmyadmin
        state: present

    
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
