---
- hosts: localhost
  tasks:

    - name: Create a scheduled task
      cron:
       name: Run employee attendance
       job: sh /opt/scripts/attendace.sh
       user: bibin
       month: 4
       day: 5
       hour: 17
       minute: 00