---
- name: Install Jenkins on Ubuntu
  hosts: test
  become: yes
  tasks:

    - name: Update apt repository and install dependencies
      apt:
        update_cache: yes
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Open port 8080 for Jenkins
      ufw:
        rule: allow
        port: 8080
        proto: tcp
      ignore_errors: yes

    - name: Display Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Show Jenkins password
      debug:
        msg: "Jenkins initial password: {{ jenkins_password.stdout }}"
